### ISSUE TITLE
The call to LexActivatorNative.GetLicenseMeterAttribute raises a TypeError exception: this function takes 3 arguments (2 given)

### ISSUE THREAD

**Issue by tcosta465** [cryptlex/lexactivator-python#1] opened 2019-08-15 14:55 UTC
https://github.com/cryptlex/lexactivator-python/blob/ab0b45747cc58eb07807ebe612764cd986818b49/cryptlex/lexactivator/lexactivator.py#L302

**Comment by adnan-kamili** [comment] 2019-08-15 17:28
Thanks for reporting. The issue is fixed now.

**Closed as completed by adnan-kamili** 2019-08-15 17:28 UTC
